# Workflow for Jest en Cypress unit tests

name: Unit and E2E Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

#       - name: Cypress run
#         uses: cypress-io/github-action@v2
#         with:
#           browser: chrome
#           headless: true
#           start: yarn serve

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test:unit
