# Workflow for Jest en Cypress unit tests

name: Unit and E2E Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Cache
        uses: actions/cache@v2.1.1
        with:
          path: node_modules
          key: ${{ runner.os }}-nodemodules 

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test:unit
